### ISSUE TITLE
Requesting to connect

### ISSUE THREAD

**Issue by Dinesh2811** [savaisolanki/GraphqlDataApplication#1]
Hi there! Myself Dinesh, I am learning to do CRUD operation with 'Graph QL' API and I saw your project which is quite interesting and its very helpful to learn Graph QL API. I very much like to connect with you if that's possible. If your ok with it then please let me know.

Any ways that's a lot for helping me understand Graph QL API request.

**Comment by savaisolanki** [comment]
yes sure bt i am also learning graphql  now,  i am trying this demo  convert into mvvm strcture , i am facing some issue when delete data.

**Comment by savaisolanki** [comment]
yes sure bt i am also learning graphql now, i am trying this demo convert into mvvm strcture , i am facing some issue when delete data.

**Comment by Dinesh2811** [comment]
Thanks a lot for the response. I would very much like to help in some way, I haven't worked on deleting the data in GraphQL as well but will try to contribute to best of my knowledge. Can we talk via Whatsapp? (You don't have to if you don't want to, But if your willing to connect via any other medium then please let me know)

My Whastapp contact is '+91 8667024800'
